#include "/Engine/Public/Platform.ush"
#include "MarchingCubesEvalFunctions.ush"

StructuredBuffer<float3> InputPoints;
RWStructuredBuffer<float> OutputVals;
float Sample(float3 pos)
{
    #include "MarchingCubesBody.ush"
}
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void GeoFlowMarchingCubes(
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint GroupIndex : SV_GroupIndex
)
{
    uint i = DispatchThreadId.x;
    OutputVals[i] = Sample(InputPoints[i]);

}
    